### ISSUE TITLE
scattergun doesn't get fully replenished on kill

### ISSUE THREAD

**Issue by maxijabase** [sapphonie/MGEMod#1]
![mgescoutbrokenammo](https://user-images.githubusercontent.com/20617661/100476751-2c9b5500-30c5-11eb-9f33-74976460a0a1.gif)

**Comment by sapphonie** [comment]
pain, this is probably caused by a race condition where it calls regenerateplayer too soon, i'll look

**Comment by sapphonie** [comment]
might be able to solve by calling `TF2_RemoveAllWeapons(client);` immediately before `TF2_RegeneratePlayer(client);`

**Comment by sapphonie** [comment]
fixed in #3
