### ISSUE TITLE
64bit support

### ISSUE THREAD

**Issue by IniZio** [sapphonie/MGEMod#18]
Since TF2 update for 64bit, MGE mode has been broken and cannot be run on servers that have migrated.

Not sure if this fork is still maintained?

**Comment by sapphonie** [comment]
Yes, it's maintained - there's no reason to update to x64 since a significant chunk of sourcemod itself still doesn't work on it... newer isn't always better, lol. MGE will be updated to work with x64 when there is a reason to do so

**Comment by IniZio** [comment]
Thanks! Let me close this first then.
