### ISSUE TITLE
Put sunshine in for final4_fix2

### ISSUE THREAD

**Issue by drago9773** [sapphonie/MGEMod#19]
Can sunshine be enabled on final4_fix2?
I see sunshine spawns is commented out in mge spawn config. I tested sunshine on older versions (b4, a8) and the arena works well. There are diagonal wall clipping but it's pretty irrelevant unless you look for it on purpose.
There is a spawn on b4 that spawns you into a rock, I believe where the 'x' value is 12800, but changing to 12700 fixes it. Not sure what the spawns on final4_fix2 are but I would be happy to test. 
I think people would play sunshine and I will be adding it to the next 2v2 cup!

**Comment by sapphonie** [comment]
Sure, I'm more than happy to accept a PR

**Comment by sapphonie** [comment]
#21
