### ISSUE TITLE
Request for mge_training_v8_beta4b map in VMF extension

### ISSUE THREAD

**Issue by fralorange** [sapphonie/MGEMod#20]
I'm working on a project that requires the 'mge_training_v8_beta4b' map in VMF extension. I've attempted to decompile the map, but it results in errors. If possible, could you provide the source VMF file, either by adding it to the repository or offering a download link? If there are any restrictions, please let me know.

**Comment by sapphonie** [comment]
I don't have it and I don't know where it is, unfortunately.

**Comment by Wheretf2** [comment]
[mge_training_v8_beta4b_d.zip](https://github.com/user-attachments/files/16229221/mge_training_v8_beta4b_d.zip)
I haven't tested the vmf outside just ensuring it opens in Hammer++, but it seems to be working fine
Decompiled from the bsp, extracted materials included
